account_id = "049ff5e84ecf636b53b162cbb580aae6"
name = "cooklog-ai"
main = "src/worker.ts"
compatibility_date = "2024-05-06"

[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"

[[kv_namespaces]]
binding = "COOKLOG_KV"
id = "09f3fb2ecae64d3bbd2976fe83e968ae"

